config/routes.rb
Rails.application.routes.draw do

  get 'creditcards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  patch 'products/edit'
  get 'searches/index'
  root to: 'top#index'
  resources :top, only: [:index, :new]

  resources :products, only: [:index, :new, :create, :edit, :show, :destroy, :update] do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
  end

  resources :creditcards, only: [:new, :create, :show, :destroy] do
    collection do
      get 'regist_done'
      get 'delete_done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :images, only: [:index, :new, :create] 

end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :user, optional: true
  validates :family_name, :first_name, :family_name_kana, :first_name_kana, 
            :postalcode, :prefecture, :city, :address, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ActiveHash::Base
  self.data = [
    { id: 1, name: "Louis Vuitton / ルイ・ヴィトン" },
    { id: 2, name: "HERMES / エルメス" },
    { id: 3, name: "CHANEL / シャネル" },
    { id: 4, name: "Dior / ディオール" },
    { id: 5, name: "SAINT LAURENT / サンローラン" },
    { id: 6, name: "GUCCI / グッチ" },
    { id: 7, name: "PRADA / プラダ" },
    { id: 8, name: "MIU MIU / ミュウミュウ" },
    { id: 9, name: "FENDI / フェンディ" },
    { id: 10, name: "Cartier / カルティエ" },
    { id: 11, name: "Tiffany / ティファニー" },
    { id: 12, name: "BVLGARI / ブルガリ" },
    { id: 13, name: "Christian louboutin / ルブタン" },
    { id: 14, name: "Jimmy Choo / ジミーチュウ" },
    { id: 15, name: "Manolo Blahnik / マノロ・ブラニク" },
    { id: 16, name: "Salvatore Ferragamo / フェラガモ"},
    { id: 17, name: "COACH / コーチ"},
    { id: 18, name: "BURBERRY / バーバリー"},
    { id: 19, name: "BALENCIAGA / バレンシアガ"},
    { id: 20, name: "Chloe / クロエ"},
    { id: 21, name: "CELINE / セリーヌ"},
    { id: 22, name: "LOEWE / ロエベ"},
    { id: 23, name: "Giorgio Armani / アルマーニ"},
    { id: 24, name: "Dolce＆Gabbana / ドルガバ"},
    { id: 25, name: "Stella McCartney / ステラ"},
    { id: 26, name: "Valentino / ヴァレンティノ"},
    { id: 27, name: "TORYBURCH / トリーバーチ"},
    { id: 28, name: "MICHAEL KORS / マイケルコース"},
    { id: 29, name: "LONGCHAMP / ロンシャン"},
    { id: 30, name: "FURLA / フルラ"},
    { id: 31, name: "UNIQLO / ユニクロ"},
    { id: 32, name: "MUJI / 無印良品"}

  ]
  include ActiveHash::Associations
  has_many :products

end

app/models/category.rb
class Category < ApplicationRecord
  def change
    add_column :categories, :name, :text
  end
  has_ancestry
  has_many :products
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: "新品・未使用" },
    { id: 2, name: "未使用に近い" },
    { id: 3, name: "目立った傷や汚れなし" },
    { id: 4, name: "やや傷や汚れあり" },
    { id: 5, name: "傷や汚れあり" },
    { id: 6, name: "全体的に状態が悪い" }
  ]
  include ActiveHash::Associations
  has_many :products

  
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user
  validates :user_id, :customer_id, :card_id, presence: true
end

app/models/days_until_shipping.rb
class DaysUntilShipping < ActiveHash::Base
  self.data = [
    { id: 1, name: "1~2日で発送" },
    { id: 2, name: "2~3日で発送" },
    { id: 3, name: "4~7日で発送" }
  ]
  include ActiveHash::Associations
  has_many :products

  
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :product 

  validates :image, presence: true

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/product.rb
class Product < ApplicationRecord

  enum status: { published: 0, sold_out: 1}
   
  validates :name, presence: true, length: {maximum:40}
  validates :description, presence: true, length: {maximum:1000}
  validates :price, presence: true
  
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, update_only: true
  validates_associated :images
  validates :images, presence: true
  
  belongs_to :user
  belongs_to :category


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :size
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :days_until_shipping
  belongs_to_active_hash :brand

  validates :condition, presence: true
  validates :size, presence: true
  validates :days_until_shipping, presence: true
  validates :shipping_charge, presence: true
  validates :prefecture, presence: true

end

app/models/profile.rb
class Profile < ApplicationRecord

  validates :first_name, :family_name, :first_name_kana, :family_name_kana, presence: true

  belongs_to :user

end

app/models/shipping_charge.rb
class ShippingCharge < ActiveHash::Base
  self.data = [
    { id: 1, name: "送料込み(出品者負担)" },
    { id: 2, name: "着払い(購入者負担)" }
  ]

  include ActiveHash::Associations
  has_many :products

end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    { id: 1, name: "サイズなし商品" },
    { id: 2, name: "XS" },
    { id: 3, name: "S" },
    { id: 4, name: "M" },
    { id: 5, name: "L" },
    { id: 6, name: "XL" },
    { id: 7, name: "FREE SIZE" }
  ]
  include ActiveHash::Associations
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 7, maximum: 128 }


  has_many :products
  has_one :address
  has_one :profile, :dependent => :destroy
  has_many :credit_card, dependent: :destroy
end

app/controllers/address_controller.rb
class AddressController < ApplicationController

def create
end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def new
    @brand = Brand.new
    @brand.products.build
  end

  def create
    @brand = Brand.new(brand_params)
  end

end

private

def brand_params
  params.require(:brand).permit(:name)
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
  end

  def new
  end

  def create
    @image = Image.new(img_up)
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @product.images.build
  end

  private
  def img_up
    params.require(:image).permit(:image, :product_id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @search = Product.ransack(params[:q])
    @products = Product.all
    @images = Image.all
    
  end

  def search
  end

  def new
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    
  end

  def show
    @card = current_user.id
    card = Creditcard.where(user_id: current_user.id).first
    if @card.blank?
      redirect_to action: :new
    end
  end

  def delete

  end

  protected

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
.wrapper
  = render 'lookbuy'

app/views/top/_appBanner.html.haml
%aside.appBanner
  .appBanner__inner
    %h2.appBanner__inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.appBanner__inner__text
      今すぐ無料ダウンロード！
    .appBanner__inner__icon
      = link_to "#", class: "aBtn" do
        = image_tag('/material/pict/app_store_badge.svg')
      = link_to "#", class: "gBtn" do
        = image_tag('/material/pict/google-play.png')

app/views/top/_footer.html.haml
.footer
  %ul.footer__contents
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAについて
      %ul
        %li
          = link_to '会社概要（運営会社)'
        %li
          = link_to "プライバシーポリシー"
        %li
          = link_to "FURIMA利用規約"
        %li
          = link_to "ポイントに関する特約"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧"
        %li
          = link_to "ブランド一覧"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド"
        %li
          = link_to "FURIMAロゴ利用ガイドライン"
        %li
          = link_to "お知らせ"
  .footer__logo
    = link_to image_tag('/material/logo/logo-white.png')
  %p ©️ FURIMA

app/views/top/_header.html.haml
%header.headerBox
  .headerBox__inner
    .headerBox__inner__main
      .headerBox__inner__main__icon
        = link_to image_tag('/material/logo/logo.png', height: '40px', class: 'headerBox__inner__main__icon__logo'), root_path
      .headerBox__inner__main__searchBox
        = search_form_for @search, url:searches_index_path, class: 'searchFormFor' do |f|
          = f.search_field :name_cont,  class: 'headerBox__inner__main__searchBox__form', placeholder: 'キーワードから探す', id: "form__box"
          %button{type: "submit", class: 'search__button'}
            = image_tag('/material/icon/icon-search 1.png')
    .headerBox__inner__nav
      %ul.listLeft
        %li.listLeft__btn
          = link_to "商品一覧", "#", id: "product-btn"
      %ul.listRight
        - if user_signed_in?
          = link_to "お気に入り"
          = link_to "お知らせ"
          = link_to "やることリスト"
          = link_to "マイページ", user_path(id: current_user.id)
        - else
          %li.listRight__item__login
            = link_to "ログイン", new_user_session_path
          %li.listRight__item__new
            = link_to "新規会員登録", new_user_registration_path

app/views/top/_main.html.haml
.main
  %section.main__visual
    .main__visual__content
      %h2.content__subtitle
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br フリマアプリです
      .content__btn
        = link_to "#", class: 'aBtn' do
          = image_tag('/material/pict/app_store_badge.svg')
        = link_to "#", class: 'gBtn' do
          = image_tag('/material/pict/google-play.png')
    .main__visual__pickture
  %section.main__introduction
    %h2.main__introduction__subtittle
      FURIMAが選ばれる３つの理由
      %after
    %ul.main__introduction__lists
      %li.main__introduction__lists__list
        .list__pict
          %span.number 1
          = image_tag('/material/pict/pict-reason-01.jpg')
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.main__introduction__lists__list
        .list__pict
          %span.number 2
          = image_tag('/material/pict/pict-reason-02.jpg')
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.main__introduction__lists__list.list--last
        .list__pict
          %span.number 3
          = image_tag('/material/pict/pict-reason-03.jpg')
        %h3.list__text
          手数料 
          %span 業界最安
        %p.list__description
          最大３％でお得に出品＆購入！
  %section.main__middle
    .main__middle__inner
      %h2.subtitle
        会員数日本一
      %p.text
        FURIMAは、フリマアプリで最も人気。
        %br 
        出品・購入回数も業界最多です！
        %br 
        ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to "#", class: 'aBtn' do
          = image_tag('/material/pict/app_store_badge.svg')
        = link_to "#", class: 'gBtn' do
          = image_tag('/material/pict/google-play.png')
  %section.main__keyFeatures
    %h2.main__keyFeatures__head
      FURIMAの特徴
      %after
    .main__keyFeatures__items
      %section.main__keyFeatures__items__item
        %figure.item__img
          = image_tag('/material/icon/icon-01.png')
        %h3.item__subtitle
          簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.main__keyFeatures__items__item
        %figure.item__img
          = image_tag('/material/icon/icon-03.png')
        %h3.item__subtitle
          売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      %section.main__keyFeatures__items__item
        %figure.item__img
          = image_tag('/material/icon/icon-04.png')
        %h3.item__subtitle
          様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけではなく、ポイントや売上金など多彩な方法があります。
  %section.main__pickupContainer
    %h2.main__pickupContainer__head
      ピックアップカテゴリー
    .main__pickupContainer__productBox
      .main__pickupContainer__productBox__head
        = link_to "#" do
          %h3.title
            新規投稿商品
      .main__pickupContainer__productBox__lists
        - @products.each do |product|
          .product__list 
            = link_to product_path(product.id) do
              %figure.product__list--img
                = image_tag product.images[0].image.url
                -if product.buyer_id.present? 
                  .product-box_photo__sold
                    .product-box_photo__sold__inner
                      SOLD
              .product__list--body
                %h3.name
                  = product.name
                .details
                  %ul
                    %li
                      = product.price
                    %li 
                      %i.fa.fa-star.lileicon
                      0
                  %p (税込)
  %section.main__pickupContainer
    %h2.main__pickupContainer__head
      ピックアップブランド
    .main__pickupContainer__productBox
      .main__pickupContainer__productBox__head
        = link_to "#" do
          %h3.title
            アーカイバ
      .main__pickupContainer__productBox__lists
        - @products.each do |product|
          .product__list 
            = link_to product_path(product.id) do
              %figure.product__list--img
                = image_tag product.images[0].image.url
                -if product.buyer_id.present? 
                  .product-box_photo__sold
                    .product-box_photo__sold__inner
                      SOLD
              .product__list--body
                %h3.name
                  = product.name
                .details
                  %ul
                    %li
                      = product.price
                    %li 
                      %i.fa.fa-star.lileicon
                      0
                  %p (税込)

app/views/top/_purchaseBtn.html.haml
= link_to new_product_path do
  .purchaseBtn
    %span.purchaseBtn__text 出品する
    = image_tag('/material/icon/icon_camera.png', class: "purchaseBtn__icon")

app/views/top/index.html.haml
.wapper
  = render 'header'
  = render 'main'
  = render 'appBanner'
  = render 'footer'
  = render 'purchaseBtn'
  