config/routes.rb
Rails.application.routes.draw do

  get 'creditcards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  patch 'products/edit'
  get 'searches/index'
  root to: 'top#index'
  resources :top, only: [:index, :new]

  resources :products, only: [:index, :new, :create, :edit, :show, :destroy, :update] do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
  end

  resources :creditcards, only: [:new, :create, :show, :destroy] do
    collection do
      get 'regist_done'
      get 'delete_done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :images, only: [:index, :new, :create] 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 7, maximum: 128 }


  has_many :products
  has_one :address
  has_one :profile, :dependent => :destroy
  has_many :credit_card, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def address_params
    params.require(:address).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postalcode, :prefecture, :city, :address, :buildingname, :phone, :birthday_date)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    
  end

  def show
    @card = current_user.id
    card = Creditcard.where(user_id: current_user.id).first
    if @card.blank?
      redirect_to action: :new
    end
  end

  def delete

  end

  protected

  
end

app/views/users/_info.html.haml
.sell__wrapper
  .sell__header
    = link_to image_tag('material/logo/logo.png', height: '60px', class: 'sell__header__logo'), root_path

  .sell__container
    .sell__container__images
      .user__conteainer__images__titles
        会員情報入力

    .entrySell__container__description
      .cautionMess
        安全・安心にご利用いただくために、お客様の本人確認情報の登録にご協力ください。
        他のお客様に公開されることはありません。

      .sell__container__description__address
        .label
          .label__content
            お名前(全角)
          .label__required
            必須
        .entryform__parallel
          %input.input-box__parallel{ placeholder: "例）振馬" }
          %input.input-box__parallel{ placeholder: "例）太郎" }

        .label
          .label__content
            お名前カナ(全角)
          .label__required
            必須
        .entryform__parallel
          %input.input-box__parallel{ placeholder: "例）フリマ" }
          %input.input-box__parallel{ placeholder: "例）タロウ" }

        .label
          .label__content
            生年月日
          .label__required
            必須
        .entryform__parallel
          %input.input-box__bod{ placeholder: "" }年
          %input.input-box__bod{ placeholder: "" }月
          %input.input-box__bod{ placeholder: "" }日
      
        .cautionMess__gray
          ※本人情報は正しく入力してください。登録後、修正するにはお時間をいただく場合がございます。
    
    .sell__container__btn
      .sell__container__btn__sell
        %button.sell-btn
          登録する
      .sell__container__btn__save
        %button.save-btn
          下書きに保存
      .sell__container__btn__return
        %a.back-link(href = root_path)
          もどる
  .sell__footer
    .sell__footer__logo
      = link_to image_tag('material/logo/logo-white.png', height: '55px', class: 'sell__footer__logo__image'), root_path
      .sell__footer__logo__block
        %a.sell__footer__logo__block__str(href = root_path) © FURIMA

app/views/users/_mypage.html.haml
.breadcrumb-list
  .breadcrumb-list__text
    .breadcrumb-list__text__home
      = link_to "FURIMA", root_path, class: "breadcrumb-list__text__home__link"
      %i.fas.fa-angle-right
    .breadcrumb-list__text__category--main
      = link_to "マイページ", "#", class: "breadcrumb-list__text__category__link--home"
   

.mypage__body
  .mypage__body__main
    .left
      .mypage-list
        %ul.mypage-list__ul
          %li.mypage-list__ul__li
            マイページ
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            いいね一覧
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            = link_to "出品する", new_product_path, class: "link_tag"
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            下書き
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 出品中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 取引中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 売却済み
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            購入した商品 - 取引中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            購入した商品 - 売却済み
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            お問い合わせ
            = icon('fas', 'angle-right')
      %h3.title
        設定
      .setting
        %ul.setting-list__ul
          %li.setting-list__ul__li
            プロフィール
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            お届け先住所
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            = link_to "支払い方法", creditcard_path(@card), class: "link_tag"
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            メール/パスワード
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            本人情報
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            電話番号の確認
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            = link_to "ログアウト", users_path, class: "link_tag"
            = icon('fas', 'angle-right')
    .right
      .right__content
        .right__content__top
          .right__content__top--a
            .a__myphoto
              = image_tag src="/assets/icon_bDa7GXd8WFkSXUMU.png", size: "60×60"
            .a__name
              = current_user.nickname
            .a__rank
              %h2.a__rank__level
                評価 0
              %h2.a__rank__item
                出品数
                = current_user.products.count
        .right__content__tabs
          %ul.tab__top
            %li.tab__top__li.info
              お知らせ
            %li.tab__top__li.todo
              やることリスト
        .right__content__naiyou
          .right__content__naiyou--a
            現在、お知らせはありません
      .right__bottom
        .right__bottom__title
          購入した商品
        %ul.right__bottom__tab__buy
          %li.right__bottom__tab__buy__li.now
            取引中
          %li.right__bottom__tab__buy__li.was
            過去の取引
        .bottom__syousai
          .bottom__syousai--x
            現在、取引はございません

app/views/users/_payment.html.haml
.sell__wrapper
  .sell__header
    = link_to image_tag('material/logo/logo.png', height: '60px', class: 'sell__header__logo'), root_path

  .sell__container
    .sell__container__images
      .user__conteainer__images__titles
        支払い方法

    .entrySell__container__description
      .sell__container__description__address
        .label
          .label__content
            カード番号
          .label__required
            必須
        .entryform__parallel
          %input.input-box{ placeholder: "半角数字のみ" }

        .label
          .label__content
            有効期限
          .label__required
            必須
        .entryform__parallel
          %input.input-box__expiration{ placeholder: "" }月
          %input.input-box__expiration{ placeholder: "" }年

        .label
          .label__content
            セキュリティコード
          .label__required
            必須
        .entryform__parallel
          %input.input-box{ placeholder: "カード背面４桁もしくは３桁の番号" }
    
    .sell__container__btn
      .sell__container__btn__sell
        %button.sell-btn
          登録する
      .sell__container__btn__return
        %a.back-link(href = root_path)
          もどる
  .sell__footer
    .sell__footer__logo
      = link_to image_tag('material/logo/logo-white.png', height: '55px', class: 'sell__footer__logo__image'), root_path
      .sell__footer__logo__block
        %a.sell__footer__logo__block__str(href = root_path) © FURIMA

app/views/users/index.html.haml
.breadcrumb-list
  .breadcrumb-list__text
    .breadcrumb-list__text__home
      = link_to "FURIMA", root_path, class: "breadcrumb-list__text__home__link"
      %i.fas.fa-angle-right
    .breadcrumb-list__text__category--main
      = link_to "マイページ", "#", class: "breadcrumb-list__text__category__link--home"
   
= render 'top/header'

.mypage__body
  .mypage__body__main
    .left
      .mypage-list
        %ul.mypage-list__ul
          %li.mypage-list__ul__li
            マイページ
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            いいね一覧
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品する
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            下書き
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 出品中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 取引中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 売却済み
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            購入した商品 - 取引中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            購入した商品 - 売却済み
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            お問い合わせ
            = icon('fas', 'angle-right')
      %h3.title
        設定
      .setting
        %ul.setting-list__ul
          %li.setting-list__ul__li
            プロフィール
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            お届け先住所
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            支払い方法
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            メール/パスワード
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            本人情報
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            電話番号の確認
            = icon('fas', 'angle-right')
    .right
      .right__item
        %button.right__item__top
          = link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "logout"
          
= render 'top/appBanner'
= render 'top/footer'

app/views/users/new.html.haml
.sell__wrapper
  .sell__header
    = link_to image_tag('material/logo/logo.png', height: '60px', class: 'sell__header__logo'), root_path

  .sell__container
    .sell__container__images
      .user__conteainer__images__titles
        登録情報入力

    .entrySell__container__description
      .sell__container__description__nickname
        .label
          .label__content
            ニックネーム
          .label__required
            必須
        %input.input-box{ placeholder: "例）振馬 太郎"}
      .sell__container__description__address
        .label
          .label__content
            メールアドレス
          .label__required
            必須
        %input.input-box{ placeholder: "PC•携帯どちらでも可" }
          .sell__container__description__password
        .label
          .label__content
            パスワード
          .label__required
            必須
        %input.input-box{ placeholder: "７文字以上の半角英数字" }
      
    
    .sell__container__btn
      .sell__container__btn__sell
        %button.sell-btn
          登録する
      .sell__container__btn__save
        %button.save-btn
          下書きに保存
      .sell__container__btn__return
        %a.back-link(href = root_path)
          もどる
  .sell__footer
    .sell__footer__logo
      = link_to image_tag('material/logo/logo-white.png', height: '55px', class: 'sell__footer__logo__image'), root_path
      .sell__footer__logo__block
        %a.sell__footer__logo__block__str(href = root_path) © FURIMA

app/views/users/show.html.haml
= render 'top/header'
= render 'users/mypage'
= render 'top/appBanner'
= render 'top/footer'