config/routes.rb
Rails.application.routes.draw do

  get 'creditcards/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  patch 'products/edit'
  get 'searches/index'
  root to: 'top#index'
  resources :top, only: [:index, :new]

  resources :products, only: [:index, :new, :create, :edit, :show, :destroy, :update] do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
    end
  end

  resources :creditcards, only: [:new, :create, :show, :destroy] do
    collection do
      get 'regist_done'
      get 'delete_done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :images, only: [:index, :new, :create] 

end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user
  validates :user_id, :customer_id, :card_id, presence: true
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  require "payjp"
  before_action :move_to_root
  before_action :set_card, only: [:new, :show, :destroy, :buy, :pay ]
  before_action :set_product, only: [:buy, :pay]
  
  def new
    if @card.present?
      redirect_to creditcard_path(current_user.id)
    else
      card = Creditcard.where(user_id: current_user.id)
    end
  end

  def create
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    if params["payjp-token"].blank?
      redirect_to new_creditcard_path, alert: "クレジットカードを登録できませんでした。"
    else
      customer = Payjp::Customer.create(
        card: params["payjp-token"],
        metadata: {user_id: current_user.id},
        description: 'test'
      )
      @card = Creditcard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to regist_done_creditcards_path
      else
        redirect_to action: :new
      end
    end
  end

  def show
    if @card.blank?
      redirect_to action: :new
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
      case @card_info.brand
      when "Visa"
        @card_src = "image-visa.png"
      when "JCB"
        @card_src = "image-JCB.png"
      when "MasterCard"
        @card_src = "image-mastercard.png"
      when "American Express"
        @card_src = "image-AMERICAN.png"
      when "Diners Club"
        @card_src = "image-Diners.png"
      end
    end
  end

  def buy
    @product = Product.find(params[:id])
    @address = Address.find(params[:id])
    if @card.blank?
    redirect_to action: :new
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(@card.card_id)
      case @card_info.brand
      when "Visa"
        @card_src = "image-visa.png"
      when "JCB"
        @card_src = "image-JCB.png"
      when "MasterCard"
        @card_src = "image-mastercard.png"
      when "American Express"
        @card_src = "image-AMERICAN.png"
      when "Diners Club"
        @card_src = "image-Diners.png"
      end
    end
  end

  def pay
    if @item.buyer_id.present?
      redirect_to product_path(@item.id), alert: "売り切れています。"
    else
      @item.with_lock do
        if @card.present?
          Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
          customer = Payjp::Customer.retrieve(@card.customer_id)
          Payjp::Charge.create(amount: @item.price, customer: customer, currency: 'jpy' )
            @item.update!(status: 1, buyer_id: current_user.id)
        else
          render action: :buy
        end
      end
    end
  end

  def destroy
    if @card.blank?
      redirect_to action: new
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      if @card.destroy
        redirect_to delete_done_creditcards_path
      else
        redirect_to creditcard_path(current_user.id), alert: "削除できませんでした。"
      end
    end
  end

  private

  def move_to_root
    redirect_to root_path unless user_signed_in?
  end

  def set_card
    @card = Creditcard.find_by(user_id: current_user.id)
  end

  def set_product
    @item = Product.find(params[:id])
  end

end

app/views/creditcards/buy.html.haml
= render "products/header"
.wrapper
  .container
    .container__images
      %h2.container__images__titles 
        購入内容の確認
    .item
      .item__image
        - @product.images.each do |i|
          = image_tag i.image.url, class:'images_table__image'
      .item__text
        %p.item__text__name
          = @product.name
        %p.item__text__money
          = @product.price
          （税込）
    .money
      .money__payment
        .money__payment__a
          支払い金額
        .money__payment__b
          = @product.price
          円
    .pay
      .pay__title
        支払い方法
      .pay__save
        クレジットカード
      .pay__save__card-number
        .card-number
          = "**** **** **** " + @card_info.last4
        .card-data
          = "有効期限" + @card_info.exp_month.to_s + " / " + @card_info.exp_year.to_s.slice(2,3) 
        .card-logo
          = image_tag "#{@card_src}", alt: @card_info.brand, class:'li-box'
    .address
      .address__title
        %h3.a
          配送先
      .address__date
        %p.number
          〒
          = @address.postalcode
        %p.possion
          = @address.prefecture
          = @address.city
          = @address.address
          = @address.buildingname
    .buy
      %p.buy__text
        郵便局/コンビニ受取をご希望の方は、購入後に取引画面から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
      %p.buy__error
        支払い方法の入力を完了してください。
        = button_to '購入する', {controller: 'creditcards', action: 'pay'}, {method: :post, class:'pay-btn'}
= render "products/footer"

app/views/creditcards/delete_done.html.haml
= render 'products/header'
.compContainer
  .compContainer__panel
    .compContainer__panel__image
      = image_tag('material/pict/info.png')
    .compContainer__panel__message
      %p クレジットカードの削除が完了しました。
      = link_to "トップページへ戻る", root_path
= render 'products/footer'

app/views/creditcards/new.html.haml
= render "products/header"

.wrapper
  .credit-card__contaier
    .credit-card__container__images
      .credit-card__container__images__text
        お支払い方法
    .credit-card__container__images
      .credit-card__container__images__box
        =form_with model: @card, id: "all-form", url: creditcards_path, local: true do |f| 
          .payment-text__box
            .payment-text__contents
              %label.credit カード番号
              %span.required 必須
            = f.text_field :card_number, placeholder: "半角数字のみ", class: 'card-number-form', maxlength: "16", id: "card_number"
            %ul.card
              %li=image_tag "image-visa.png", class: 'li-box'
              %li=image_tag "image-mastercard.png", class: 'li-box'
              %li=image_tag "image-JCB.png", class: 'li-box'
              %li=image_tag "image-AMERICAN.png", class: 'li-box'
              %li=image_tag "image-Diners.png", class: 'li-box'
            .expiration__payment__date
              %label.credit 有効期限
              %span.required 必須
            .expiration__payment__form
              = f.select :exp_month, [["01", 1],["02", 2],["03", 3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]], id: "exp_month"
              .exp-text 月
              = f.select :exp_year, [["2020", 2020],["2021", 2021],["2022", 2022],["2023",2023],["2024",2024],["2025",2025],["2026",2026],["2027",2027],["2028",2028],["2029",2029],["2030",2030]], id: "exp_year"
              .exp-text 年
            .payment-text__contents
              %label.credit セキュリティコード
              %span.required 必須
            = f.text_field :security_code, placeholder: "カード背面４桁または３桁の番号", class: 'payment-text-container', maxlength: "4", id: "security_code" 
            .card
              .card__token
                =f.submit "登録する", class: "credit-card-submit-btn", id: "charge_form"
              .sell__container__btn__return
                %a.back-link(href = "javascript:history.back()")
                  もどる

= render "products/footer"

app/views/creditcards/pay.html.haml
= render 'products/header'
.compContainer
  .compContainer__panel
    .compContainer__panel__image
      = image_tag('material/pict/info.png')
    .compContainer__panel__message
      %p 商品の購入が完了しました。
      = link_to "トップページへ戻る", root_path
= render 'products/footer'

app/views/creditcards/regist_done.html.haml
= render 'products/header'
.compContainer
  .compContainer__panel
    .compContainer__panel__image
      = image_tag('material/pict/info.png')
    .compContainer__panel__message
      %p クレジットカードの登録が完了しました。
      = link_to "トップページへ戻る", root_path
= render 'products/footer'

app/views/creditcards/show.html.haml
.breadcrumb-list
  .breadcrumb-list__text
    .breadcrumb-list__text__home
      = link_to "FURIMA", root_path, class: "breadcrumb-list__text__home__link"
      %i.fas.fa-angle-right
    .breadcrumb-list__text__category--main
      = link_to "マイページ", "#", class: "breadcrumb-list__text__category__link--home"
   
= render 'top/header'

.mypage__body
  .mypage__body__main
    .left
      .mypage-list
        %ul.mypage-list__ul
          %li.mypage-list__ul__li
            マイページ
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            いいね一覧
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品する
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            下書き
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 出品中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 取引中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            出品した商品 - 売却済み
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            購入した商品 - 取引中
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            購入した商品 - 売却済み
            = icon('fas', 'angle-right')
          %li.mypage-list__ul__li
            お問い合わせ
            = icon('fas', 'angle-right')
      %h3.title
        設定
      .setting
        %ul.setting-list__ul
          %li.setting-list__ul__li
            プロフィール
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            お届け先住所
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            支払い方法
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            メール/パスワード
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            本人情報
            = icon('fas', 'angle-right')
          %li.setting-list__ul__li
            電話番号の確認
            = icon('fas', 'angle-right')
    .right
      .delete__box
        .delete__box__header
          お支払い方法
        .delete__box__container
          .delete__box__container__card-data
            .delete__box__cotainer__card-date__text
              クレジットカード
            %ul.delete__box__container__card-data__area
              %li.delete__box__container__card-data__area__list
                .card-date
                  .card-date__box
                    .card-number
                      = "**** **** **** " + @card_info.last4
                    .card-data
                      = "有効期限" + @card_info.exp_month.to_s + " / " + @card_info.exp_year.to_s.slice(2,3) 
                    .card-logo
                      = image_tag "#{@card_src}", alt: @card_info.brand, class:'li-box'
                  .car-btn
                    = button_to "削除する", {controller: 'creditcards', action: 'destroy'}, {method: :delete, class:'delete-btn'}
          
= render 'top/appBanner'
= render 'top/footer'